In [1]:
# PROGRAM DESCRIPTION: [The code includes a short refresher of the inputs used earlier]
# AUTHOR INFORMATION:
# Written by: [Zen Adrian Tandogon]
# Date: [2/12/23]
# Time: [10:13]
# Program: [BSDS]
# Course: [CS158-1L]
# School: [MAPUA]

In [3]:
import numpy as np

In [5]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [7]:
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [12]:
np.full(20, 5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [16]:
arr=np.arange(0,70)

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69])

In [21]:
arr=np.arange(0,70,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68])

In [29]:
arr=np.arange(10,19)
arr
arr.reshape(3,3)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [30]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
np.random.randn(50)

array([-0.05616477,  0.68578858, -0.14480183, -0.16397107,  0.50893698,
       -0.5656662 ,  0.17132471, -1.768179  ,  1.91962286, -1.12504603,
       -0.45759428, -0.08487811, -2.00049401, -0.94094832, -0.376387  ,
        1.81428724,  1.20123365, -1.1255846 ,  0.98002575, -0.61944324,
       -1.29444723, -0.72867888,  0.39453979, -0.5658234 , -0.34815274,
       -0.087408  , -0.16827354, -0.59723945, -0.51778868,  0.72634177,
        0.20944364,  0.79118739,  0.83751806, -0.28094702,  0.39676774,
       -2.12820217, -1.41577006,  1.28497219, -1.45665605,  0.56165385,
       -0.26223181, -0.0470251 ,  0.2933034 , -1.84391158, -0.68724502,
       -0.64820593,  0.50742841, -0.11723369, -1.70814127,  2.48270996])

In [35]:
matrix = np.arange(1,51).reshape(5,10)
matrix

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [36]:
arr.sum()

126

In [38]:
arr.std()

2.581988897471611