In [26]:
# PROGRAM DESCRIPTION: [The following set of inputs are creating samples of an array and getting the values of range and overall working with array.]
# AUTHOR INFORMATION:# Written by: [Zen Adrian Tandogon]
# Date: [2/12/23]
# Time: [Current Time]
# Program: [BSDS]
# Course: [CS158-1]
# School: [MAPUA]

In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[0:5]=100

arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [8]:
arr = np.arange(0,11)

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arr_copy = arr.copy()
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [14]:
arr_2d[1]

array([20, 25, 30])

In [15]:
arr_2d[1][0]

20

In [16]:
arr_2d[1,0]

20

In [17]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [18]:
arr_2d[2]

array([35, 40, 45])

In [19]:
arr_2d[2,:]

array([35, 40, 45])

In [20]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [22]:
bool_arr = arr>4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [23]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [24]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])