In [49]:
# PROGRAM DESCRIPTION: [The inputs are lists, arrays, and random. The code works with linspace, matrices, and mainly arrays.]

In [ ]:
#Written by: [Zen Adrian Tandogon]

In [3]:
#12-2-23

In [4]:
#BSDS

In [5]:
#CS158-1L_A1

In [7]:
#MAPUA

In [10]:
# The first thing to know is that when we're using numpy, we must import it.# It should be easy just to install Conda, install Numpy or Pip Numpy where you run# that at your command line# once you've already installed it, go ahead and type out import numpy and all#lowercase as# and then by convention we import numpy as 
import numpy as np

In [12]:
# For example, if I say my list is equal to a standard python list of one, two, three,# and then I check the type of my list, it's currently just a list type to# transform something into a numpy. I can say np array and then pass in# what I want to transform, and now you'll notice the output looks# different and our outputs, it is showing that it's a numpy.

my_list = [1,2,3]
my_array = np.array([1,2,3])

In [13]:
type(my_list)

list

In [14]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [15]:
np.array(my_list)

array([1, 2, 3])

In [16]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [17]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [20]:
np.zeros(3)

array([0., 0., 0.])

In [21]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones(3)

array([1., 1., 1.])

In [23]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [25]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [26]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [27]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
np.random.rand(2)

array([0.69510763, 0.40221869])

In [29]:
np.random.rand(5,5)

array([[0.66951835, 0.65374569, 0.63983949, 0.21331437, 0.42731698],
       [0.81323624, 0.92278771, 0.6229215 , 0.53332675, 0.81532996],
       [0.04084283, 0.81145412, 0.26317632, 0.44888803, 0.58037404],
       [0.37784265, 0.4442491 , 0.60939874, 0.19852062, 0.27841388],
       [0.06670886, 0.61321106, 0.27368601, 0.26465516, 0.60691116]])

In [30]:
np.random.randn(2)

array([ 1.1938973, -1.4213337])

In [31]:
np.random.randn(5,5)

array([[-0.80926173,  1.21596988,  1.31635158, -0.03786515, -0.25412034],
       [-0.39785307, -0.027855  ,  0.55618477,  1.05421534, -2.25695654],
       [-0.47941349, -0.65196677,  0.58909972, -0.8283525 , -0.14384778],
       [-0.7514775 , -1.79540856, -0.91114517,  0.5493109 ,  2.46773601],
       [ 0.79235375,  1.74377861, -0.33718312, -0.02178841, -1.63741034]])

In [32]:
np.random.randint(1,100)

12

In [33]:
np.random.randint(1,100,10)

array([23, 22, 81, 88, 24,  9, 66, 92, 20, 89])

In [34]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [35]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [38]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [40]:
ranarr.max()

39

In [41]:
ranarr.argmax()

7

In [42]:
ranarr.min()

2

In [43]:
ranarr.argmin()

9

In [44]:
# Vector
arr.shape

(25,)

In [45]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [46]:
arr.reshape(1,25).shape

(1, 25)

In [47]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [48]:
arr.reshape(25,1).shape

(25, 1)